/** Collapsible filter section titles — Men / Women / Kids (marketplace-style). */

export const FILTER_SECTIONS_MEN = [
  "Color",
  "Size",
  "Brand",
  "Category",
  "Type",
  "Occasion",
  "Prints & patterns",
  "Offers",
  "Set of",
  "Material",
  "Fit",
  "Sleeve",
  "Neck type",
  "Waist rise",
  "Length",
  "Men T Shirt",
  "No Of Pcs",
  "Persona",
  "Type of pleat",
  "Flat Front",
  "Pleated",
  "Shade",
  "Transparency of the fabric",
  "Pockets",
  "Print & pattern",
  "Closure",
  "Work",
  "Lowest priced",
  "Collar",
  "Features",
  "Neck",
  "Hood",
  "Hooded",
  "Dress length",
];

export const FILTER_SECTIONS_WOMEN = [
  "Color",
  "Size",
  "Brand",
  "Category",
  "Type",
  "Occasion",
  "Prints & patterns",
  "Offers",
  "Material",
  "Blouse attached",
  "Fit",
  "Set of",
  "Neck type",
  "Sleeve",
  "Work",
  "Wiring",
  "Waist rise",
  "Neck",
  "Padding",
  "Bottom Type",
  "Straps",
  "Coverage",
  "Top Type",
  "No Of Pcs",
  "Sleeve type",
  "Length",
  "Lowest priced",
  "Size (In meters)",
  "Kurta length",
  "Ethnic Set",
  "Pattern",
  "Dress length",
  "Seam",
  "Closure",
  "Women T Shirt",
  "Ideal for",
  "Pallu",
  "Trim",
  "Pleat type",
  "Shade",
  "Bra type",
  "Persona",
  "Panty type",
  "Blouse piece",
  "Garment type",
  "Pockets",
  "Tunic length",
  "Slit type",
  "Style",
  "Prints and pattern",
  "Essential",
];

export const FILTER_SECTIONS_KIDS = [
  "Color",
  "Size",
  "Brand",
  "Category",
  "Type",
  "Occasion",
  "Prints & patterns",
  "Offers",
  "Material",
  "Neck type",
  "Sleeve",
  "Set of",
  "No Of Pcs",
  "Upper Type",
  "Bottom Type",
  "Fit",
  "Lowest priced",
  "Neck",
];

export function getFilterSectionsForCategory(categoryLabel) {
  const k = categoryLabel?.toLowerCase() || "";
  if (k === "men") return FILTER_SECTIONS_MEN;
  if (k === "women") return FILTER_SECTIONS_WOMEN;
  if (k === "kids" || k === "babies") return FILTER_SECTIONS_KIDS;
  if (k === "elderly") return FILTER_SECTIONS_WOMEN;
  return FILTER_SECTIONS_WOMEN;
}
